apiVersion: serving.knative.dev/v1 
kind: Service
metadata:
  name: skaffold-knative-npm
  namespace: default 
spec:
  template:
    spec:
      containers:
        - image: dev.local/skaffold-knative
          # env:
          #   - name: TARGET 
          #     value: "Go Sample v1"
